<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Candidat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Candidat_model');
    } 

    /*
     * Listing of candidats
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('candidat/index?');
        $config['total_rows'] = $this->Candidat_model->get_all_candidats_count();
        $this->pagination->initialize($config);

        $data['candidats'] = $this->Candidat_model->get_all_candidats($params);
        
        $data['_view'] = 'candidat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new candidat
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('noms','Noms','required');
		$this->form_validation->set_rules('sexe','Sexe','required');
		$this->form_validation->set_rules('etatCivil','EtatCivil','required');
		$this->form_validation->set_rules('telephone','Telephone','is_unique[candidats.telephone]');
		$this->form_validation->set_rules('dateNaissance','DateNaissance','required');
		$this->form_validation->set_rules('lieuNaissance','LieuNaissance','required');
		$this->form_validation->set_rules('niveauEtude','NiveauEtude','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'sexe' => $this->input->post('sexe'),
				'etatCivil' => $this->input->post('etatCivil'),
				'noms' => $this->input->post('noms'),
				'adresse' => $this->input->post('adresse'),
				'telephone' => $this->input->post('telephone'),
				'dateNaissance' => $this->input->post('dateNaissance'),
				'lieuNaissance' => $this->input->post('lieuNaissance'),
				'profession' => $this->input->post('profession'),
				'niveauEtude' => $this->input->post('niveauEtude'),
            );
            
            $candidat_id = $this->Candidat_model->add_candidat($params);
            redirect('candidat/index');
        }
        else
        {            
            $data['_view'] = 'candidat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a candidat
     */
    function edit($cand_id)
    {   
        // check if the candidat exists before trying to edit it
        $data['candidat'] = $this->Candidat_model->get_candidat($cand_id);
        
        if(isset($data['candidat']['cand_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('noms','Noms','required');
			$this->form_validation->set_rules('sexe','Sexe','required');
			$this->form_validation->set_rules('etatCivil','EtatCivil','required');
			$this->form_validation->set_rules('telephone','Telephone','is_unique[candidats.telephone]');
			$this->form_validation->set_rules('dateNaissance','DateNaissance','required');
			$this->form_validation->set_rules('lieuNaissance','LieuNaissance','required');
			$this->form_validation->set_rules('niveauEtude','NiveauEtude','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'sexe' => $this->input->post('sexe'),
					'etatCivil' => $this->input->post('etatCivil'),
					'noms' => $this->input->post('noms'),
					'adresse' => $this->input->post('adresse'),
					'telephone' => $this->input->post('telephone'),
					'dateNaissance' => $this->input->post('dateNaissance'),
					'lieuNaissance' => $this->input->post('lieuNaissance'),
					'profession' => $this->input->post('profession'),
					'niveauEtude' => $this->input->post('niveauEtude'),
                );

                $this->Candidat_model->update_candidat($cand_id,$params);            
                redirect('candidat/index');
            }
            else
            {
                $data['_view'] = 'candidat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The candidat you are trying to edit does not exist.');
    } 

    /*
     * Deleting candidat
     */
    function remove($cand_id)
    {
        $candidat = $this->Candidat_model->get_candidat($cand_id);

        // check if the candidat exists before trying to delete it
        if(isset($candidat['cand_id']))
        {
            $this->Candidat_model->delete_candidat($cand_id);
            redirect('candidat/index');
        }
        else
            show_error('The candidat you are trying to delete does not exist.');
    }
    
}
