<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Domaine extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Domaine_model');
    } 

    /*
     * Listing of domaines
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('domaine/index?');
        $config['total_rows'] = $this->Domaine_model->get_all_domaines_count();
        $this->pagination->initialize($config);

        $data['domaines'] = $this->Domaine_model->get_all_domaines($params);
        
        $data['_view'] = 'domaine/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new domaine
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('intituleDom','IntituleDom','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'dateAjout' => $this->input->post('dateAjout'),
				'intituleDom' => $this->input->post('intituleDom'),
				'observation' => $this->input->post('observation'),
            );
            
            $domaine_id = $this->Domaine_model->add_domaine($params);
            redirect('domaine/index');
        }
        else
        {            
            $data['_view'] = 'domaine/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a domaine
     */
    function edit($dom_id)
    {   
        // check if the domaine exists before trying to edit it
        $data['domaine'] = $this->Domaine_model->get_domaine($dom_id);
        
        if(isset($data['domaine']['dom_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('intituleDom','IntituleDom','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'dateAjout' => $this->input->post('dateAjout'),
					'intituleDom' => $this->input->post('intituleDom'),
					'observation' => $this->input->post('observation'),
                );

                $this->Domaine_model->update_domaine($dom_id,$params);            
                redirect('domaine/index');
            }
            else
            {
                $data['_view'] = 'domaine/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The domaine you are trying to edit does not exist.');
    } 

    /*
     * Deleting domaine
     */
    function remove($dom_id)
    {
        $domaine = $this->Domaine_model->get_domaine($dom_id);

        // check if the domaine exists before trying to delete it
        if(isset($domaine['dom_id']))
        {
            $this->Domaine_model->delete_domaine($dom_id);
            redirect('domaine/index');
        }
        else
            show_error('The domaine you are trying to delete does not exist.');
    }
    
}
