<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Facture extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Facture_model');
    } 

    /*
     * Listing of factures
     */
    function index()
    {
        $data['factures'] = $this->Facture_model->get_all_factures();
        
        $data['_view'] = 'facture/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new facture
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'numer_facture' => $this->input->post('numer_facture'),
				'date_facture' => $this->input->post('date_facture'),
				'net_a_payer' => $this->input->post('net_a_payer'),
				'client_sid' => $this->input->post('client_sid'),
				'etat_facture' => $this->input->post('etat_facture'),
            );
            
            $facture_id = $this->Facture_model->add_facture($params);
            redirect('facture/index');
        }
        else
        {            
            $data['_view'] = 'facture/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a facture
     */
    function edit($fac_id)
    {   
        // check if the facture exists before trying to edit it
        $data['facture'] = $this->Facture_model->get_facture($fac_id);
        
        if(isset($data['facture']['fac_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'numer_facture' => $this->input->post('numer_facture'),
					'date_facture' => $this->input->post('date_facture'),
					'net_a_payer' => $this->input->post('net_a_payer'),
					'client_sid' => $this->input->post('client_sid'),
					'etat_facture' => $this->input->post('etat_facture'),
                );

                $this->Facture_model->update_facture($fac_id,$params);            
                redirect('facture/index');
            }
            else
            {
                $data['_view'] = 'facture/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The facture you are trying to edit does not exist.');
    } 

    /*
     * Deleting facture
     */
    function remove($fac_id)
    {
        $facture = $this->Facture_model->get_facture($fac_id);

        // check if the facture exists before trying to delete it
        if(isset($facture['fac_id']))
        {
            $this->Facture_model->delete_facture($fac_id);
            redirect('facture/index');
        }
        else
            show_error('The facture you are trying to delete does not exist.');
    }
    
}
