<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Intervention extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Intervention_model');
    } 

    /*
     * Listing of interventions
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('intervention/index?');
        $config['total_rows'] = $this->Intervention_model->get_all_interventions_count();
        $this->pagination->initialize($config);

        $data['interventions'] = $this->Intervention_model->get_all_interventions($params);
        
        $data['_view'] = 'intervention/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new intervention
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('formateur_sid','Formateur Sid','required');
		$this->form_validation->set_rules('formation_sid','Formation Sid','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'formateur_sid' => $this->input->post('formateur_sid'),
				'formation_sid' => $this->input->post('formation_sid'),
				'dateInterv' => $this->input->post('dateInterv'),
				'statutInter' => $this->input->post('statutInter'),
				'effectifCandidats' => $this->input->post('effectifCandidats'),
				'matiereVue' => $this->input->post('matiereVue'),
				'observation' => $this->input->post('observation'),
            );
            
            $intervention_id = $this->Intervention_model->add_intervention($params);
            redirect('intervention/index');
        }
        else
        {
			$this->load->model('Formateur_model');
			$data['all_formateurs'] = $this->Formateur_model->get_all_formateurs();

			$this->load->model('Formation_model');
			$data['all_formations'] = $this->Formation_model->get_all_formations();
            
            $data['_view'] = 'intervention/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a intervention
     */
    function edit($inter_id)
    {   
        // check if the intervention exists before trying to edit it
        $data['intervention'] = $this->Intervention_model->get_intervention($inter_id);
        
        if(isset($data['intervention']['inter_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('formateur_sid','Formateur Sid','required');
			$this->form_validation->set_rules('formation_sid','Formation Sid','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'formateur_sid' => $this->input->post('formateur_sid'),
					'formation_sid' => $this->input->post('formation_sid'),
					'dateInterv' => $this->input->post('dateInterv'),
					'statutInter' => $this->input->post('statutInter'),
					'effectifCandidats' => $this->input->post('effectifCandidats'),
					'matiereVue' => $this->input->post('matiereVue'),
					'observation' => $this->input->post('observation'),
                );

                $this->Intervention_model->update_intervention($inter_id,$params);            
                redirect('intervention/index');
            }
            else
            {
				$this->load->model('Formateur_model');
				$data['all_formateurs'] = $this->Formateur_model->get_all_formateurs();

				$this->load->model('Formation_model');
				$data['all_formations'] = $this->Formation_model->get_all_formations();

                $data['_view'] = 'intervention/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The intervention you are trying to edit does not exist.');
    } 

    /*
     * Deleting intervention
     */
    function remove($inter_id)
    {
        $intervention = $this->Intervention_model->get_intervention($inter_id);

        // check if the intervention exists before trying to delete it
        if(isset($intervention['inter_id']))
        {
            $this->Intervention_model->delete_intervention($inter_id);
            redirect('intervention/index');
        }
        else
            show_error('The intervention you are trying to delete does not exist.');
    }
    
}
