<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Brevet_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get brevet by brev_id
     */
    function get_brevet($brev_id)
    {
        return $this->db->get_where('brevets',array('brev_id'=>$brev_id))->row_array();
    }
    
    /*
     * Get all brevets count
     */
    function get_all_brevets_count()
    {
        $this->db->from('brevets');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all brevets
     */
    function get_all_brevets($params = array())
    {
        $this->db->order_by('brev_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('brevets')->result_array();
    }
        
    /*
     * function to add new brevet
     */
    function add_brevet($params)
    {
        $this->db->insert('brevets',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update brevet
     */
    function update_brevet($brev_id,$params)
    {
        $this->db->where('brev_id',$brev_id);
        return $this->db->update('brevets',$params);
    }
    
    /*
     * function to delete brevet
     */
    function delete_brevet($brev_id)
    {
        return $this->db->delete('brevets',array('brev_id'=>$brev_id));
    }
}
