<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Candidat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get candidat by cand_id
     */
    function get_candidat($cand_id)
    {
        return $this->db->get_where('candidats',array('cand_id'=>$cand_id))->row_array();
    }
    
    /*
     * Get all candidats count
     */
    function get_all_candidats_count()
    {
        $this->db->from('candidats');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all candidats
     */
    function get_all_candidats($params = array())
    {
        $this->db->order_by('cand_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('candidats')->result_array();
    }
        
    /*
     * function to add new candidat
     */
    function add_candidat($params)
    {
        $this->db->insert('candidats',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update candidat
     */
    function update_candidat($cand_id,$params)
    {
        $this->db->where('cand_id',$cand_id);
        return $this->db->update('candidats',$params);
    }
    
    /*
     * function to delete candidat
     */
    function delete_candidat($cand_id)
    {
        return $this->db->delete('candidats',array('cand_id'=>$cand_id));
    }
}
