<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Domaine_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get domaine by dom_id
     */
    function get_domaine($dom_id)
    {
        return $this->db->get_where('domaines',array('dom_id'=>$dom_id))->row_array();
    }
    
    /*
     * Get all domaines count
     */
    function get_all_domaines_count()
    {
        $this->db->from('domaines');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all domaines
     */
    function get_all_domaines($params = array())
    {
        $this->db->order_by('dom_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('domaines')->result_array();
    }
        
    /*
     * function to add new domaine
     */
    function add_domaine($params)
    {
        $this->db->insert('domaines',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update domaine
     */
    function update_domaine($dom_id,$params)
    {
        $this->db->where('dom_id',$dom_id);
        return $this->db->update('domaines',$params);
    }
    
    /*
     * function to delete domaine
     */
    function delete_domaine($dom_id)
    {
        return $this->db->delete('domaines',array('dom_id'=>$dom_id));
    }
}
