<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Formateur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get formateur by ens_id
     */
    function get_formateur($ens_id)
    {
        return $this->db->get_where('formateurs',array('ens_id'=>$ens_id))->row_array();
    }
    
    /*
     * Get all formateurs count
     */
    function get_all_formateurs_count()
    {
        $this->db->from('formateurs');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all formateurs
     */
    function get_all_formateurs($params = array())
    {
        $this->db->order_by('ens_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('formateurs')->result_array();
    }
        
    /*
     * function to add new formateur
     */
    function add_formateur($params)
    {
        $this->db->insert('formateurs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update formateur
     */
    function update_formateur($ens_id,$params)
    {
        $this->db->where('ens_id',$ens_id);
        return $this->db->update('formateurs',$params);
    }
    
    /*
     * function to delete formateur
     */
    function delete_formateur($ens_id)
    {
        return $this->db->delete('formateurs',array('ens_id'=>$ens_id));
    }
}
