<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Intervention_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get intervention by inter_id
     */
    function get_intervention($inter_id)
    {
        return $this->db->get_where('interventions',array('inter_id'=>$inter_id))->row_array();
    }
    
    /*
     * Get all interventions count
     */
    function get_all_interventions_count()
    {
        $this->db->from('interventions');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all interventions
     */
    function get_all_interventions($params = array())
    {
        $this->db->order_by('inter_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('interventions')->result_array();
    }
        
    /*
     * function to add new intervention
     */
    function add_intervention($params)
    {
        $this->db->insert('interventions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update intervention
     */
    function update_intervention($inter_id,$params)
    {
        $this->db->where('inter_id',$inter_id);
        return $this->db->update('interventions',$params);
    }
    
    /*
     * function to delete intervention
     */
    function delete_intervention($inter_id)
    {
        return $this->db->delete('interventions',array('inter_id'=>$inter_id));
    }
}
